function com_google_collaboration_tables_DataSourceMod(){var N='bootstrap',O='begin',P='gwt.codesvr.com.google.collaboration.tables.DataSourceMod=',Q='gwt.codesvr=',R='com.google.collaboration.tables.DataSourceMod',S='startup',T='DUMMY',U=0,V='body',W='iframe',X='javascript:""',Y='position:absolute; width:0; height:0; border:none; left: -1000px;',Z=' top: -1000px;',$='CSS1Compat',_='<!doctype html>',ab='',bb='<html><head><\/head><body><\/body><\/html>',cb='undefined',db=/loaded|complete/,eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib=1,jb='");',kb='script',lb='javascript',mb='moduleStartup',nb='moduleRequested',ob='head',pb='meta',qb='name',rb='com.google.collaboration.tables.DataSourceMod::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb=/^\w+:\/\//,Fb='img',Gb='clear.cache.gif',Hb='baseUrl',Ib='com.google.collaboration.tables.DataSourceMod.nocache.js',Jb='base',Kb='//',Lb=/^\//,Mb=/^[a-zA-Z]+:\/\//,Nb='user.agent',Ob='webkit',Pb='safari',Qb='msie',Rb=10,Sb='ie10',Tb=9,Ub='ie9',Vb=8,Wb='ie8',Xb='gecko',Yb='gecko1_8',Zb='unknown',$b=2,_b=3,ac=4,bc='selectingPermutation',cc='com.google.collaboration.tables.DataSourceMod.devmode.js',dc='4697DD6B65C43DC3B051A63F8E94FFC3',ec='51419736F7687AB81A3E17936DBBD270',fc='66A60A33D0FF3BEA6CF30F5998783631',gc='7DBC56283DFA006ACB0865A7BD9F7252',hc='CBB69B323C93C0EE4398309EBC444B55',ic=':',jc='.cache.js',kc='loadExternalRefs',lc='end',mc='http:',nc='file:',oc='__gwtDevModeHook:com.google.collaboration.tables.DataSourceMod',pc=/^https?:\/\/(localhost|[a-zA-Z0-9.-]+\.(corp|prod)\.google\.com):[0-9]+\/.*$/,qc='Ignoring non-whitelisted Dev Mode URL: ',rc=':moduleBase';var o=window;var p=document;r(N,O);function q(){var a=o.location.search;return a.indexOf(P)!=-1||a.indexOf(Q)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:R,sessionId:o.__gwtStatsSessionId,subSystem:S,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_google_collaboration_tables_DataSourceMod.__sendStats=r;com_google_collaboration_tables_DataSourceMod.__moduleName=R;com_google_collaboration_tables_DataSourceMod.__errFn=null;com_google_collaboration_tables_DataSourceMod.__moduleBase=T;com_google_collaboration_tables_DataSourceMod.__softPermutationId=U;com_google_collaboration_tables_DataSourceMod.__computePropValue=null;com_google_collaboration_tables_DataSourceMod.__getPropMap=null;com_google_collaboration_tables_DataSourceMod.__gwtInstallCode=function(){};com_google_collaboration_tables_DataSourceMod.__gwtStartLoadingFragment=function(){return null};com_google_collaboration_tables_DataSourceMod.__gwt_isKnownPropertyValue=function(){return false};com_google_collaboration_tables_DataSourceMod.__gwt_getMetaProperty=function(){return null};__propertyErrorFunction=null;var s=o.__gwt_activeModules=o.__gwt_activeModules||{};s[R]={moduleName:R};var t;function u(){w();return t}
function v(){w();return t.getElementsByTagName(V)[U]}
function w(){if(t){return}var a=p.createElement(W);a.src=X;a.id=R;a.style.cssText=Y+Z;a.tabIndex=-1;p.body.appendChild(a);t=a.contentDocument;if(!t){t=a.contentWindow.document}t.open();var b=document.compatMode==$?_:ab;t.write(b+bb);t.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==cb){return typeof p.body!=cb&&p.body!=null}return db.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=u();var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(hb));for(var i=U;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(ib,j.length-ib)))}h.appendChild(f.createTextNode(jb));g=f.createElement(kb);g.language=lb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=U;i<c.length;i++){g=f.createElement(kb);g.language=lb;g.text=c[i];e.appendChild(g);d(e,g)}}}
com_google_collaboration_tables_DataSourceMod.onScriptDownloaded=function(a){l(function(){m(a)})};r(mb,nb);var n=p.createElement(kb);n.src=k;p.getElementsByTagName(ob)[U].appendChild(n)}
com_google_collaboration_tables_DataSourceMod.__startLoadingFragment=function(a){return D(a)};com_google_collaboration_tables_DataSourceMod.__installRunAsyncCode=function(a){var b=v();var c=u().createElement(kb);c.language=lb;c.text=a;b.appendChild(c);b.removeChild(c)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=U,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,ab);if(j.indexOf(sb)>=U){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=U){j=k.substring(U,m);l=k.substring(m+ib)}else{j=k;l=ab}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;com_google_collaboration_tables_DataSourceMod.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=U?a.substring(U,d+ib):ab}
function f(a){if(a.match(Eb)){}else{var b=p.createElement(Fb);b.src=a+Gb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Hb);if(a!=null){return a}return ab}
function h(){var a=p.getElementsByTagName(kb);for(var b=U;b<a.length;++b){if(a[b].src.indexOf(Ib)!=-1){return e(a[b].src)}}return ab}
function i(){var a=p.getElementsByTagName(Jb);if(a.length>U){return a[a.length-ib].href}return ab}
function j(){var a=p.location;return a.href==a.protocol+Kb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(Lb)){return a}if(a.match(Mb)){return a}return com_google_collaboration_tables_DataSourceMod.__moduleBase+a}
function F(){var f=[];var g;function h(a,b){var c=f;for(var d=U,e=a.length-ib;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Nb]=function(){var a=navigator.userAgent.toLowerCase();if(function(){return a.indexOf(Ob)!=-1}())return Pb;if(function(){return a.indexOf(Qb)!=-1&&p.documentMode==Rb}())return Sb;if(function(){return a.indexOf(Qb)!=-1&&p.documentMode>=Tb}())return Ub;if(function(){return a.indexOf(Qb)!=-1&&p.documentMode>=Vb}())return Wb;if(function(){return a.indexOf(Xb)!=-1}())return Yb;return Zb};i[Nb]={gecko1_8:U,ie10:ib,ie8:$b,ie9:_b,safari:ac};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};com_google_collaboration_tables_DataSourceMod.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};com_google_collaboration_tables_DataSourceMod.__computePropValue=k;o.__gwt_activeModules[R].bindings=com_google_collaboration_tables_DataSourceMod.__getPropMap;r(N,bc);if(q()){return D(cc)}var l;try{h([Sb],dc);h([Yb],ec);h([Pb],fc);h([Ub],gc);h([Wb],hc);l=f[k(Nb)];var m=l.indexOf(ic);if(m!=-1){g=parseInt(l.substring(m+ib),Rb);l=l.substring(U,m)}}catch(a){}com_google_collaboration_tables_DataSourceMod.__softPermutationId=g;return D(l+jc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(kc,O);r(kc,lc)}
B();com_google_collaboration_tables_DataSourceMod.__moduleBase=C();s[R].moduleBase=com_google_collaboration_tables_DataSourceMod.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==mc||o.location.protocol==nc);o.__gwt_activeModules[R].canRedirect=I;if(I){var J=oc;var K=o.sessionStorage[J];if(!pc.test(K)){if(K&&(window.console&&console.log)){console.log(qc+K)}K=ab}if(K&&!o[J]){o[J]=true;o[J+rc]=C();var L=p.createElement(kb);L.src=K;var M=p.getElementsByTagName(ob)[U];M.insertBefore(L,M.firstElementChild||M.children[U]);return false}}}G();r(N,lc);A(H);return true}
com_google_collaboration_tables_DataSourceMod.succeeded=com_google_collaboration_tables_DataSourceMod();